//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlluringDecors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int Id { get; set; }
        public int ServiceRequestId { get; set; }
        public double Price { get; set; }
        public string Note { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual service_request service_request { get; set; }
    }
}
