//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlluringDecors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_domain
    {
        public service_domain()
        {
            this.service_request = new HashSet<service_request>();
        }
    
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int DomainId { get; set; }
    
        public virtual domain domain { get; set; }
        public virtual service service { get; set; }
        public virtual ICollection<service_request> service_request { get; set; }
    }
}
