//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlluringDecors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_request
    {
        public service_request()
        {
            this.bills = new HashSet<bill>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ServiceDomainId { get; set; }
        public string Receiver { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public System.DateTime dateSent { get; set; }
    
        public virtual ICollection<bill> bills { get; set; }
        public virtual service_domain service_domain { get; set; }
        public virtual user user { get; set; }
    }
}
