//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlluringDecors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.feedbacks = new HashSet<feedback>();
            this.service_request = new HashSet<service_request>();
            this.user_role = new HashSet<user_role>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phonenumber { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<service_request> service_request { get; set; }
        public virtual ICollection<user_role> user_role { get; set; }
    }
}
